### ISSUE TITLE
bug: navbar is not working a expected

### ISSUE THREAD

**Issue by lokesh-wagh** [GDSC-UPES/GDSC-UPES-Website#22]
the navbar route's are not working as expected 

expected behaviour :
as the route change's the content's should be displayed

actual behaviour : 
route's are changing but the page component are not actually being rendered

[screen-capture (1).webm](https://github.com/GDSC-UPES/GDSC-UPES-Website/assets/129964049/13a97dcb-0ce7-48ef-ad85-af695325d195)

Steps to reproduce :
1. go the website url
2. click on any navigation button's in the navbar

**Comment by lokesh-wagh** [comment]
I have liunked the pull request that will close this issue

can the maintainer's please take a look and review it

**Comment by hustlerZzZ** [comment]
Fixed this in #14

**Comment by lokesh-wagh** [comment]
Ok 
Thanks
